# Generated by Django 2.0.2 on 2018-02-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fio',
        ),
    ]
