# Generated by Django 2.0.2 on 2018-02-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180202_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
