# Generated by Django 2.0.2 on 2018-02-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180202_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
