# Generated by Django 2.0.2 on 2018-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180202_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='drink',
            field=models.TextField(null=True),
        ),
    ]
